# Generated by Django 5.1.5 on 2025-02-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('hint', models.TextField()),
                ('meaning', models.TextField()),
                ('translation', models.TextField()),
                ('translated_definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('correct_guesses_count', models.IntegerField(default=0)),
                ('played_words', models.ManyToManyField(blank=True, to='ZHed.word')),
            ],
        ),
    ]
