# Generated by Django 5.1.5 on 2025-02-17 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
