# Generated by Django 5.1.5 on 2025-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHed', '0002_alter_word_options_word_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamestate', models.BooleanField(default=True)),
                ('halfgamestate', models.BooleanField(default=False)),
            ],
        ),
    ]
