# Generated by Django 5.1.5 on 2025-03-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHed', '0003_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='dormant',
            field=models.BooleanField(default=False),
        ),
    ]
