# Generated by Django 5.1.5 on 2025-03-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHed', '0004_states_dormant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
