# Generated by Django 5.1.5 on 2025-03-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZHed', '0005_alter_word_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='correct_guesses_count',
        ),
    ]
