# Generated by Django 5.1.5 on 2025-03-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHed', '0006_remove_player_correct_guesses_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correct_guesses_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
