# Generated by Django 5.1.5 on 2025-03-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZHed', '0008_remove_player_correct_guesses_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='played_words',
            field=models.ManyToManyField(blank=True, related_name='players', to='ZHed.word'),
        ),
    ]
